###Simple request 
GET http://localhost:3000/element

###Find one element
GET http://localhost:3000/element/1
###Simple POST test request
POST http://localhost:3000/element HTTP/1.1
Content-Type: application/json
//This line have to be non written

{
    "name":"Test Switchboard 2",
    "connection":[
        {
            "label":"A29091" 
        },
        {
            "label":"N23201"
        }
    ]
}
###Update 
PATCH http://localhost:3000/element/19 HTTP/1.1
Content-Type: application/json

{
    "id":19,
    "name":"Test Switchboard Update Test"
}
### Delete
DELETE  http://localhost:3000/element/2

### Delete all
DELETE   http://localhost:3000/element/

//------------------- Connection Entity -------
###Home Request
GET http://localhost:3000/connection

###Get all connections
GET http://localhost:3000/connection/all

### Create Test Connection
POST http://localhost:3000/connection HTTP/1.1
Content-Type: application/json
//This line have to be non written

{
    "id":"1",
    "label":"A029131"
}

###Delete Testing Connection
DELETE http://localhost:3000/connection/

###Clean up

DELETE http://localhost:3000/connection/1
